version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: moc
      MONGO_INITDB_ROOT_PASSWORD: moc
    volumes:
      - ./db:/data/db
    ports:
      - 27017:27017

  nginx:
    image: nginx
    volumes:
      - ./server:/var/www
      - ./server/nginx.conf:/etc/nginx/nginx.conf
      - ./server/certbot/conf:/etc/letsencrypt
      - ./server/certbot/www:/var/www/certbot
    network_mode: "host" # to access Flask server
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    volumes:
      - ./server/certbot/conf:/etc/letsencrypt
      - ./server/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
